// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
)

const getFeed = `-- name: GetFeed :many
SELECT id, sender, recipient, content, read, created_at FROM messages
WHERE (? = '' OR sender = ?)
  AND (? = '' OR recipient = ?)
  AND (? = 0 OR read = 0)
ORDER BY created_at DESC
LIMIT ? OFFSET ?
`

type GetFeedParams struct {
	Column1   interface{} `json:"column_1"`
	Sender    string      `json:"sender"`
	Column3   interface{} `json:"column_3"`
	Recipient string      `json:"recipient"`
	Column5   interface{} `json:"column_5"`
	Limit     int64       `json:"limit"`
	Offset    int64       `json:"offset"`
}

func (q *Queries) GetFeed(ctx context.Context, arg GetFeedParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getFeed,
		arg.Column1,
		arg.Sender,
		arg.Column3,
		arg.Recipient,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Sender,
			&i.Recipient,
			&i.Content,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInbox = `-- name: GetInbox :many
SELECT id, sender, recipient, content, read, created_at FROM messages
WHERE recipient = ? AND read = 0
ORDER BY created_at DESC
`

func (q *Queries) GetInbox(ctx context.Context, recipient string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getInbox, recipient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Sender,
			&i.Recipient,
			&i.Content,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, sender, recipient, content, read, created_at FROM messages
WHERE id = ?
`

func (q *Queries) GetMessageByID(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Sender,
		&i.Recipient,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}

const markRead = `-- name: MarkRead :exec
UPDATE messages
SET read = 1
WHERE id = ?
`

func (q *Queries) MarkRead(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markRead, id)
	return err
}

const sendMessage = `-- name: SendMessage :one
INSERT INTO messages (id, sender, recipient, content)
VALUES (?, ?, ?, ?)
RETURNING id, sender, recipient, content, read, created_at
`

type SendMessageParams struct {
	ID        string `json:"id"`
	Sender    string `json:"sender"`
	Recipient string `json:"recipient"`
	Content   string `json:"content"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, sendMessage,
		arg.ID,
		arg.Sender,
		arg.Recipient,
		arg.Content,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Sender,
		&i.Recipient,
		&i.Content,
		&i.Read,
		&i.CreatedAt,
	)
	return i, err
}
